### ISSUE TITLE
Wallet configurator

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#39]
For now we are not going to creat graphical wallet configurator.

We will use yaml format for creating it.

**Comment by stanbar** [comment]
What kind of configuration should be in it ?

**Comment by PatrykMilewski** [comment]
@stasbar it should look like Docker-Compose yaml, atleast for modules:

```
version: '0.1'

modules:

  pin:
    max-retry: 5
    instances: 3      # parallel modules

  authorization-server:
    hostname: 89.89.89.89
    port: 8080
    endpoints:
      set-secret: /authorization/secret/set
      overwritte-secret: /authorization/secret/overwritte
    https: true
    
  button:
    some: configuration
    
wallet:
  autolock-time: 1800
  etc: etc

```
